version: '3'
services:

  server:
    build: .
    ports:
      - "1080:1080"
    environment:
      DB_CREDS: "root:password@tcp(database)/sbvision"
      ASSET_DIR: "/data"
      PORT: ":1080"
      FRONTEND_DIR: "/go/src/github.com/kevinwylder/sbvision/frontend"

    volumes:
      - ${PWD}/:/go/src/github.com/kevinwylder/sbvision
      - ${PWD}/data:/data
    
    command: sleep 999999999999

  database:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ${PWD}/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3369:3306"
