version: '3'
services:

  server:
    build: .
    ports:
      - "1080:1080"
    environment:
      DB_CREDS: "root:password@tcp(database)/skateboardvision"
      ASSET_DIR: "/data"
      PORT: "3000"

    volumes:
      - ${PWD}/:/go/src/github.com/kevinwylder/sbvision
      - ${PWD}/data:/data

    working_dir: "/go/src/github.com/kevinwylder/sbvision"
    command: "gin -p 1080 -a 3000 -d ./cmd/server run main.go"

  database:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ${PWD}/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3369:3306"
